"""
Django settings for pylucy project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&$%woawra(l*0b-smspn3744q10h#oeazoz+fq_2fk$14z!kjn'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split() or ["localhost", "127.0.0.1"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_select2',
    'django_celery_beat',  # Tareas programadas con BD
    'alumnos',
    'cursos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'pylucy.middleware.NoCacheMiddleware',  # Deshabilitar caché en desarrollo
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pylucy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'pylucy' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pylucy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", "pylucy"),
        "USER": os.getenv("DB_USER", "pylucy"),
        "PASSWORD": os.getenv("DB_PASSWORD", "pylucy"),
        "HOST": os.getenv("DB_HOST", "localhost"),  # en Docker será "db"
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Configuración de la API SIAL/UTI (mock o producción)
SIAL_BASE_URL = os.getenv("SIAL_BASE_URL", "http://localhost:8088").rstrip("/")
SIAL_BASIC_USER = os.getenv("SIAL_BASIC_USER", "usuario")
SIAL_BASIC_PASS = os.getenv("SIAL_BASIC_PASS", "contrasena")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True

# Regional formatting for Argentina
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "."


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # /app/static/ cuando se monta ./src:/app
    BASE_DIR / 'pylucy' / 'static',  # /app/pylucy/static/ - archivos CSS personalizados del admin
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin site customization
ADMIN_SITE_HEADER = "Lucy AMS"
ADMIN_SITE_TITLE = "Lucy Admin"
ADMIN_INDEX_TITLE = "Panel de Administración"

# Email configuration
# =============================================================================
# CONFIGURACIÓN DE EMAIL (Office 365 / SMTP)
# =============================================================================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Office 365 SMTP: smtp.office365.com:587 (TLS)
# MailHog (dev): mailhog:1025 (sin auth)
EMAIL_HOST = os.getenv("EMAIL_HOST", "mailhog")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "1025"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("EMAIL_FROM", "no-reply@v.eco.unrc.edu.ar")
EMAIL_FROM = DEFAULT_FROM_EMAIL  # Alias para consistencia

ALLOWED_HOSTS = ['*']

# =============================================================================
# CONFIGURACIÓN TESTING vs PRODUCCIÓN (#ETME)
# =============================================================================

# Modo de ejecución (testing o production)
ENVIRONMENT_MODE = os.getenv("ENVIRONMENT_MODE", "testing").lower()

# Prefijo para cuentas de testing
# testing: test-a12345678@eco.unrc.edu.ar
# production: a12345678@eco.unrc.edu.ar
ACCOUNT_PREFIX = "test-a" if ENVIRONMENT_MODE == "testing" else "a"

# Moodle
MOODLE_BASE_URL = os.getenv(
    "MOODLE_BASE_URL",
    "https://sandbox.moodledemo.net" if ENVIRONMENT_MODE == "testing" else "https://moodle.eco.unrc.edu.ar"
)
MOODLE_WSTOKEN = os.getenv("MOODLE_WSTOKEN", "")

# Microsoft Teams / Graph API
TEAMS_TENANT = os.getenv("TEAMS_TENANT", "")  # Tenant ID (GUID)
TEAMS_DOMAIN = os.getenv("TEAMS_DOMAIN", "eco.unrc.edu.ar")  # Dominio para UPNs
TEAMS_CLIENT_ID = os.getenv("TEAMS_CLIENT_ID", "")
TEAMS_CLIENT_SECRET = os.getenv("TEAMS_CLIENT_SECRET", "")

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
