"""
Nombre del Módulo: 0001_initial.py

Descripción:
Migración de base de datos generada por Django.

Autor: Carlos Dagorret
Fecha de Creación: 2025-12-29
Última Modificación: 2025-12-29

Licencia: MIT
Copyright (c) 2025 Carlos Dagorret

Permisos:
Se concede permiso, de forma gratuita, a cualquier persona que obtenga una copia
de este software y la documentación asociada (el "Software"), para tratar
en el Software sin restricciones, incluyendo, sin limitación, los derechos
de usar, copiar, modificar, fusionar, publicar, distribuir, sublicenciar
y/o vender copias del Software, y para permitir a las personas a las que
se les proporciona el Software hacerlo, sujeto a las siguientes condiciones:

El aviso de copyright anterior y este aviso de permiso se incluirán en todas
las copias o partes sustanciales del Software.

EL SOFTWARE SE PROPORCIONA "TAL CUAL", SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O
IMPLÍCITA, INCLUYENDO PERO NO LIMITADO A LAS GARANTÍAS DE COMERCIABILIDAD,
IDONEIDAD PARA UN PROPÓSITO PARTICULAR Y NO INFRACCIÓN. EN NINGÚN CASO LOS
AUTORES O TITULARES DE LOS DERECHOS DE AUTOR SERÁN RESPONSABLES DE CUALQUIER
RECLAMO, DAÑO U OTRA RESPONSABILIDAD, YA SEA EN UNA ACCIÓN DE CONTRATO,
AGRAVIO O DE OTRO MODO, QUE SURJA DE, FUERA DE O EN CONEXIÓN CON EL SOFTWARE
O EL USO U OTROS TRATOS EN EL SOFTWARE.
"""
# Generated by hand for initial Alumno model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo_documento", models.CharField(max_length=20)),
                ("dni", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("email_personal", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("cohorte", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("localidad", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("email_institucional", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "estado_actual",
                    models.CharField(
                        choices=[
                            ("preinscripto", "Preinscripto"),
                            ("aspirante", "Aspirante"),
                            ("ingresante", "Ingresante"),
                            ("alumno", "Alumno"),
                        ],
                        default="preinscripto",
                        max_length=15,
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("estado_ingreso", models.CharField(blank=True, max_length=100, null=True)),
                ("modalidad_actual", models.CharField(blank=True, max_length=1, null=True)),
                ("teams_password", models.CharField(blank=True, max_length=255, null=True)),
                ("teams_payload", models.JSONField(blank=True, null=True)),
                ("fecha_ultima_modificacion", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "ordering": ("apellido", "nombre"),
                "unique_together": {("tipo_documento", "dni")},
            },
        ),
    ]
