# Generated by hand for initial Alumno model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo_documento", models.CharField(max_length=20)),
                ("dni", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("email_personal", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("cohorte", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("localidad", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("email_institucional", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "estado_actual",
                    models.CharField(
                        choices=[
                            ("preinscripto", "Preinscripto"),
                            ("aspirante", "Aspirante"),
                            ("ingresante", "Ingresante"),
                            ("alumno", "Alumno"),
                        ],
                        default="preinscripto",
                        max_length=15,
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("estado_ingreso", models.CharField(blank=True, max_length=100, null=True)),
                ("modalidad_actual", models.CharField(blank=True, max_length=1, null=True)),
                ("teams_password", models.CharField(blank=True, max_length=255, null=True)),
                ("teams_payload", models.JSONField(blank=True, null=True)),
                ("fecha_ultima_modificacion", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "ordering": ("apellido", "nombre"),
                "unique_together": {("tipo_documento", "dni")},
            },
        ),
    ]
