# Generated by Django 5.2.9 on 2025-12-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='moodle_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
