# Generated by Django 5.2.9 on 2025-12-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_email_payload_alumno_moodle_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito'), ('DEBUG', 'Debug')], db_index=True, default='INFO', max_length=10)),
                ('modulo', models.CharField(db_index=True, help_text='Módulo o servicio que generó el log (ej: teams_service, email_service)', max_length=100)),
                ('mensaje', models.TextField(help_text='Mensaje descriptivo del evento')),
                ('detalles', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True)),
                ('usuario', models.CharField(blank=True, help_text='Usuario que ejecutó la acción (opcional)', max_length=150, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alumno', models.ForeignKey(blank=True, help_text='Alumno relacionado con el evento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Log de Sistema',
                'verbose_name_plural': 'Logs de Sistema',
                'ordering': ('-fecha',),
                'indexes': [models.Index(fields=['-fecha', 'tipo'], name='alumnos_log_fecha_3e2513_idx'), models.Index(fields=['modulo', '-fecha'], name='alumnos_log_modulo_96244a_idx')],
            },
        ),
    ]
