# Generated by Django 5.2.9 on 2025-12-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preinscriptos_dia_inicio', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para iniciar ingesta de preinscriptos (1-31). Vacío = no ejecutar', null=True)),
                ('preinscriptos_dia_fin', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para detener ingesta de preinscriptos (1-31). Vacío = sin límite', null=True)),
                ('preinscriptos_frecuencia_segundos', models.PositiveIntegerField(default=3600, help_text='Frecuencia de ingesta de preinscriptos en segundos (default: 3600 = 1 hora)')),
                ('aspirantes_dia_inicio', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para iniciar ingesta de aspirantes (1-31). Vacío = no ejecutar', null=True)),
                ('aspirantes_dia_fin', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para detener ingesta de aspirantes (1-31). Vacío = sin límite', null=True)),
                ('aspirantes_frecuencia_segundos', models.PositiveIntegerField(default=3600, help_text='Frecuencia de ingesta de aspirantes en segundos (default: 3600 = 1 hora)')),
                ('ingresantes_dia_inicio', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para iniciar ingesta de ingresantes (1-31). Vacío = no ejecutar', null=True)),
                ('ingresantes_dia_fin', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes para detener ingesta de ingresantes (1-31). Vacío = sin límite', null=True)),
                ('ingresantes_frecuencia_segundos', models.PositiveIntegerField(default=3600, help_text='Frecuencia de ingesta de ingresantes en segundos (default: 3600 = 1 hora)')),
                ('teams_tenant_id', models.CharField(blank=True, help_text='Tenant ID de Azure AD (GUID). Si está vacío, usa variable de entorno', max_length=255)),
                ('teams_client_id', models.CharField(blank=True, help_text='Client ID de Teams App. Si está vacío, usa variable de entorno', max_length=255)),
                ('teams_client_secret', models.CharField(blank=True, help_text='Client Secret de Teams App. Si está vacío, usa variable de entorno', max_length=255)),
                ('moodle_base_url', models.URLField(blank=True, help_text='URL base de Moodle. Si está vacío, usa variable de entorno', max_length=255)),
                ('moodle_wstoken', models.CharField(blank=True, help_text='Token de Moodle WebServices. Si está vacío, usa variable de entorno', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
