# Generated by Django 5.2.9 on 2025-12-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_configuracion'),
    ]

    operations = [
        # Eliminar campos viejos (smallint)
        migrations.RemoveField(
            model_name='configuracion',
            name='preinscriptos_dia_inicio',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='preinscriptos_dia_fin',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='aspirantes_dia_inicio',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='aspirantes_dia_fin',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='ingresantes_dia_inicio',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='ingresantes_dia_fin',
        ),

        # Crear campos nuevos (timestamp)
        migrations.AddField(
            model_name='configuracion',
            name='preinscriptos_dia_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para iniciar ingesta de preinscriptos. Vacío = no ejecutar', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='preinscriptos_dia_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para detener ingesta de preinscriptos. Vacío = sin límite', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='aspirantes_dia_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para iniciar ingesta de aspirantes. Vacío = no ejecutar', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='aspirantes_dia_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para detener ingesta de aspirantes. Vacío = sin límite', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ingresantes_dia_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para iniciar ingesta de ingresantes. Vacío = no ejecutar', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ingresantes_dia_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para detener ingesta de ingresantes. Vacío = sin límite', null=True),
        ),
    ]
