# Generated by Django 5.2.9 on 2025-12-11 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_configuracion_aspirantes_dia_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingesta_preinscriptos', 'Ingesta de Preinscriptos'), ('ingesta_aspirantes', 'Ingesta de Aspirantes'), ('ingesta_ingresantes', 'Ingesta de Ingresantes'), ('eliminar_cuenta', 'Eliminar Cuenta Externa'), ('enviar_email', 'Enviar Email'), ('activar_servicios', 'Activar Servicios (Teams+Email)'), ('crear_usuario_teams', 'Crear Usuario en Teams'), ('resetear_password', 'Resetear Contraseña')], db_index=True, help_text='Tipo de tarea ejecutada', max_length=30)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completada'), ('failed', 'Fallida')], db_index=True, default='pending', help_text='Estado actual de la tarea', max_length=15)),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tarea en Celery', max_length=255, null=True, unique=True)),
                ('hora_programada', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Cuándo se creó/programó la tarea')),
                ('hora_inicio', models.DateTimeField(blank=True, help_text='Cuándo empezó a ejecutarse', null=True)),
                ('hora_fin', models.DateTimeField(blank=True, help_text='Cuándo terminó de ejecutarse', null=True)),
                ('cantidad_entidades', models.PositiveIntegerField(default=0, help_text='Cantidad de entidades afectadas (alumnos creados, emails enviados, etc.)')),
                ('detalles', models.JSONField(blank=True, help_text='Información adicional sobre la tarea (resultados, errores, etc.)', null=True)),
                ('usuario', models.CharField(blank=True, help_text='Usuario que inició la tarea (opcional)', max_length=150, null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la tarea falló', null=True)),
                ('alumno', models.ForeignKey(blank=True, help_text='Alumno relacionado con la tarea (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Tarea Asíncrona',
                'verbose_name_plural': 'Tareas Asíncronas',
                'ordering': ('-hora_programada',),
                'indexes': [models.Index(fields=['-hora_programada', 'estado'], name='alumnos_tar_hora_pr_c9b7ae_idx'), models.Index(fields=['tipo', '-hora_programada'], name='alumnos_tar_tipo_8a28ed_idx'), models.Index(fields=['estado', 'tipo'], name='alumnos_tar_estado_b630a5_idx')],
            },
        ),
    ]
