# Generated by Django 5.2.9 on 2025-12-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='batch_size',
            field=models.PositiveIntegerField(default=20, help_text='Cantidad de alumnos a procesar por lote (recomendado: 10-30)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='rate_limit_moodle',
            field=models.PositiveIntegerField(default=30, help_text='Máximo de tareas Moodle por minuto (recomendado: 20-50)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='rate_limit_teams',
            field=models.PositiveIntegerField(default=10, help_text='Máximo de tareas Teams por minuto (recomendado: 5-15, no exceder 20)'),
        ),
    ]
