# Generated by Django 5.2.9 on 2025-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_add_batch_and_rate_limit_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Email remitente para notificaciones. Si está vacío, usa DEFAULT_FROM_EMAIL de entorno', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_host',
            field=models.CharField(blank=True, help_text='Servidor SMTP para envío de emails. Si está vacío, usa EMAIL_HOST de entorno', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, help_text='Puerto SMTP (ej: 587 para TLS, 465 para SSL). Si está vacío, usa EMAIL_PORT de entorno', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_use_tls',
            field=models.BooleanField(blank=True, help_text='Usar TLS para conexión SMTP. Si es NULL, usa EMAIL_USE_TLS de entorno', null=True),
        ),
    ]
