# Generated by Django 5.2.9 on 2025-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_add_email_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='account_prefix',
            field=models.CharField(blank=True, help_text="Prefijo para cuentas (ej: 'test-a' para testing, 'a' para producción). Si está vacío, usa variable de entorno", max_length=20),
        ),
    ]
