# Generated by Django 5.2.9 on 2025-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_configuracion_account_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carreras_data',
            field=models.JSONField(blank=True, help_text='Array de carreras tal como viene de la API UTI/SIAL (id_carrera, nombre_carrera, modalidad, comisiones)', null=True),
        ),
    ]
