# Generated by Django 5.2.9 on 2025-12-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_alumno_carreras_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='moodle_email_type',
            field=models.CharField(choices=[('institucional', 'Email Institucional'), ('personal', 'Email Personal')], default='institucional', help_text='Tipo de email a usar para enrollment en Moodle', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='moodle_student_roleid',
            field=models.PositiveIntegerField(default=5, help_text='Role ID de estudiante en Moodle (default: 5, verificar en tu instalación)'),
        ),
    ]
