# Generated by Django 5.2.9 on 2025-12-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_add_moodle_email_and_roleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='sial_base_url',
            field=models.URLField(blank=True, help_text='URL base de API SIAL/UTI (ej: https://sial.unrc.edu.ar o http://mock-api-uti:8000). Si está vacío, usa variable de entorno', max_length=255),
        ),
    ]
