# Generated by Django 5.2.9 on 2025-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_add_sial_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='sial_basic_pass',
            field=models.CharField(blank=True, help_text='Contraseña para autenticación básica en API SIAL/UTI. Si está vacío, usa variable de entorno', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='sial_basic_user',
            field=models.CharField(blank=True, help_text='Usuario para autenticación básica en API SIAL/UTI. Si está vacío, usa variable de entorno', max_length=255),
        ),
    ]
