# Generated by Django 5.2.9 on 2025-12-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_add_sial_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='moodle_procesado',
            field=models.BooleanField(default=False, help_text='Indica si el alumno ya fue procesado en Moodle (usuario creado y enrollado en cursos)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='teams_procesado',
            field=models.BooleanField(default=False, help_text='Indica si el alumno ya fue procesado en Teams (usuario creado y licencia asignada)'),
        ),
    ]
