# Generated by Django 5.2.9 on 2025-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_add_procesado_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email_plantilla_bienvenida',
            field=models.TextField(blank=True, help_text='Plantilla HTML para email de bienvenida (preinscriptos/aspirantes). Variables: {nombre}, {apellido}, {dni}, {email}'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_plantilla_credenciales',
            field=models.TextField(blank=True, help_text='Plantilla HTML para email con credenciales Teams. Variables: {nombre}, {apellido}, {upn}, {password}'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_plantilla_password',
            field=models.TextField(blank=True, help_text='Plantilla HTML para email de reseteo de password. Variables: {nombre}, {apellido}, {upn}, {password}'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='moodle_auth_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('oauth2', 'OAuth2 (Microsoft)')], default='oauth2', help_text="Método de autenticación en Moodle: 'manual' o 'oauth2' (Microsoft Teams)", max_length=20),
        ),
    ]
