# Generated by Django 5.2.9 on 2025-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0016_populate_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('ingesta_preinscriptos', 'Ingesta de Preinscriptos'), ('ingesta_aspirantes', 'Ingesta de Aspirantes'), ('ingesta_ingresantes', 'Ingesta de Ingresantes'), ('eliminar_cuenta', 'Eliminar Cuenta Externa'), ('enviar_email', 'Enviar Email'), ('activar_servicios', 'Activar Servicios (Teams+Email)'), ('crear_usuario_teams', 'Crear Usuario en Teams'), ('resetear_password', 'Resetear Contraseña'), ('moodle_enroll', 'Enrollar en Moodle')], db_index=True, help_text='Tipo de tarea ejecutada', max_length=30),
        ),
    ]
