# Generated by Django 5.2.9 on 2025-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0017_alter_tarea_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='moodle_auth_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('oauth2', 'OAuth2 (Microsoft)'), ('oidc', 'OpenID Connect')], default='oidc', help_text="Método de autenticación en Moodle: 'manual', 'oauth2' (Microsoft Teams), o 'oidc' (OpenID Connect)", max_length=20),
        ),
    ]
