# Generated by Django 5.2.9 on 2025-12-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_add_oidc_auth_method'),
    ]

    operations = [
        # Modificar el on_delete de Tarea.alumno para que sea SET_NULL en la DB
        migrations.AlterField(
            model_name='tarea',
            name='alumno',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='tareas',
                to='alumnos.alumno'
            ),
        ),
        # Modificar el on_delete de Log.alumno para que sea SET_NULL en la DB
        migrations.AlterField(
            model_name='log',
            name='alumno',
            field=models.ForeignKey(
                blank=True,
                help_text='Alumno relacionado con este log (opcional)',
                null=True,
                on_delete=models.SET_NULL,
                related_name='logs',
                to='alumnos.alumno'
            ),
        ),
    ]
