# Generated by Django 5.2.9 on 2025-12-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0019_fix_tarea_foreign_key'),
    ]

    operations = [
        # Forzar actualización del constraint ON DELETE a SET NULL
        migrations.RunSQL(
            sql="""
                ALTER TABLE alumnos_tarea
                DROP CONSTRAINT IF EXISTS alumnos_tarea_alumno_id_941acd7c_fk_alumnos_alumno_id;

                ALTER TABLE alumnos_tarea
                ADD CONSTRAINT alumnos_tarea_alumno_id_941acd7c_fk_alumnos_alumno_id
                FOREIGN KEY (alumno_id) REFERENCES alumnos_alumno(id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE alumnos_tarea
                DROP CONSTRAINT IF EXISTS alumnos_tarea_alumno_id_941acd7c_fk_alumnos_alumno_id;

                ALTER TABLE alumnos_tarea
                ADD CONSTRAINT alumnos_tarea_alumno_id_941acd7c_fk_alumnos_alumno_id
                FOREIGN KEY (alumno_id) REFERENCES alumnos_alumno(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
        # Lo mismo para Log.alumno
        migrations.RunSQL(
            sql="""
                ALTER TABLE alumnos_log
                DROP CONSTRAINT IF EXISTS alumnos_log_alumno_id_8b9e6c4a_fk_alumnos_alumno_id;

                ALTER TABLE alumnos_log
                ADD CONSTRAINT alumnos_log_alumno_id_8b9e6c4a_fk_alumnos_alumno_id
                FOREIGN KEY (alumno_id) REFERENCES alumnos_alumno(id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE alumnos_log
                DROP CONSTRAINT IF EXISTS alumnos_log_alumno_id_8b9e6c4a_fk_alumnos_alumno_id;

                ALTER TABLE alumnos_log
                ADD CONSTRAINT alumnos_log_alumno_id_8b9e6c4a_fk_alumnos_alumno_id
                FOREIGN KEY (alumno_id) REFERENCES alumnos_alumno(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
