# Generated by Django 5.2.9 on 2025-12-13 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0020_fix_foreign_key_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='alumno',
            field=models.ForeignKey(blank=True, help_text='Alumno relacionado con el evento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='alumno',
            field=models.ForeignKey(blank=True, help_text='Alumno relacionado con la tarea (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='alumnos.alumno'),
        ),
    ]
