# Generated by Django 5.2.9 on 2025-12-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0021_alter_log_alumno_alter_tarea_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='rate_limit_uti',
            field=models.PositiveIntegerField(default=60, help_text='🔧 Máximo de llamadas a API UTI/SIAL por minuto (recomendado: 30-100)'),
        ),
    ]
