# Generated by Django 5.2.9 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0022_add_rate_limit_uti'),
    ]

    operations = [
        # Agregar campos de asunto para cada tipo de email
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_bienvenida',
            field=models.CharField(
                blank=True,
                default='Bienvenido/a a la UNRC',
                max_length=255,
                help_text='Asunto del email de bienvenida. Variables: {nombre}, {apellido}, {dni}'
            ),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_credenciales',
            field=models.CharField(
                blank=True,
                default='Credenciales de acceso - UNRC',
                max_length=255,
                help_text='Asunto del email de credenciales. Variables: {nombre}, {apellido}, {upn}'
            ),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_password',
            field=models.CharField(
                blank=True,
                default='Nueva contraseña - UNRC',
                max_length=255,
                help_text='Asunto del email de reseteo de password. Variables: {nombre}, {apellido}, {upn}'
            ),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_enrollamiento',
            field=models.CharField(
                blank=True,
                default='Acceso al Ecosistema Virtual - UNRC',
                max_length=255,
                help_text='Asunto del email de enrollamiento Moodle. Variables: {nombre}, {apellido}'
            ),
        ),
        # Agregar plantilla para enrollamiento
        migrations.AddField(
            model_name='configuracion',
            name='email_plantilla_enrollamiento',
            field=models.TextField(
                blank=True,
                help_text='Plantilla HTML para email de enrollamiento en Moodle. Variables: {nombre}, {apellido}, {upn}, {moodle_url}, {cursos_html}. Pegar HTML completo.'
            ),
        ),
        # Actualizar help_text de plantillas existentes
        migrations.AlterField(
            model_name='configuracion',
            name='email_plantilla_bienvenida',
            field=models.TextField(
                blank=True,
                help_text='Plantilla HTML para email de bienvenida (preinscriptos/aspirantes). Variables: {nombre}, {apellido}, {dni}, {email}. Pegar HTML completo.'
            ),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='email_plantilla_credenciales',
            field=models.TextField(
                blank=True,
                help_text='Plantilla HTML para email con credenciales Teams. Variables: {nombre}, {apellido}, {upn}, {password}. Pegar HTML completo.'
            ),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='email_plantilla_password',
            field=models.TextField(
                blank=True,
                help_text='Plantilla HTML para email de reseteo de password. Variables: {nombre}, {apellido}, {upn}, {password}. Pegar HTML completo.'
            ),
        ),
    ]
