# Generated by Django 5.2.9 on 2025-12-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0022_add_rate_limit_uti'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email_procesado',
            field=models.BooleanField(default=False, help_text='Indica si se envió email de bienvenida/credenciales al alumno exitosamente'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='aspirantes_enviar_email',
            field=models.BooleanField(default=True, help_text='✉️ Enviar emails a aspirantes durante ingesta automática (bienvenida + credenciales + enrollamiento)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ingresantes_enviar_email',
            field=models.BooleanField(default=True, help_text='✉️ Enviar email de enrollamiento a ingresantes durante ingesta automática'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='preinscriptos_enviar_email',
            field=models.BooleanField(default=True, help_text='✉️ Enviar email de bienvenida a preinscriptos durante ingesta automática'),
        ),
    ]

