# Generated by Django 5.2.9 on 2025-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0024_add_email_subjects_and_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='moodle_courses_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de cursos Moodle por estado de alumno. Formato: {"preinscripto": ["curso1"], "aspirante": ["I1", "I2"], "ingresante": ["curso3"]}'),
        ),
    ]
