# Generated by Django 5.2.9 on 2025-12-25 23:00

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    """Agrega campos solo si no existen (migración idempotente para resolver conflictos)"""
    from django.db import connection

    with connection.cursor() as cursor:
        # Verificar qué columnas existen
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='alumnos_configuracion'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Lista de campos a agregar con sus definiciones SQL
        fields_to_add = [
            ('deshabilitar_fallback_email_personal', "BOOLEAN DEFAULT FALSE"),
            ('email_asunto_bienvenida', "VARCHAR(255) DEFAULT 'Bienvenido/a a la UNRC'"),
            ('email_asunto_credenciales', "VARCHAR(255) DEFAULT 'Credenciales de acceso - UNRC'"),
            ('email_asunto_password', "VARCHAR(255) DEFAULT 'Nueva contraseña - UNRC'"),
            ('email_asunto_enrollamiento', "VARCHAR(255) DEFAULT 'Acceso al Ecosistema Virtual - UNRC'"),
            ('email_plantilla_enrollamiento', "TEXT DEFAULT ''"),
        ]

        # Agregar solo las columnas que no existen
        for field_name, field_definition in fields_to_add:
            if field_name not in existing_columns:
                cursor.execute(f"""
                    ALTER TABLE alumnos_configuracion
                    ADD COLUMN {field_name} {field_definition}
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0025_configuracion_moodle_courses_config'),
    ]

    operations = [
        # Usar migración personalizada para agregar campos de forma idempotente
        migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
    ]
