# Generated by Django 5.2.9 on 2025-12-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0025_configuracion_moodle_courses_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='deshabilitar_fallback_email_personal',
            field=models.BooleanField(default=False, help_text='⚠️ Si está activado, NO usa email personal como fallback cuando falta email institucional. Sistema loguea advertencia y rechaza operación.'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_bienvenida',
            field=models.CharField(blank=True, default='Bienvenido/a a la UNRC', help_text='Asunto del email de bienvenida. Variables: {nombre}, {apellido}, {dni}', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_credenciales',
            field=models.CharField(blank=True, default='Credenciales de acceso - UNRC', help_text='Asunto del email de credenciales. Variables: {nombre}, {apellido}, {upn}', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_enrollamiento',
            field=models.CharField(blank=True, default='Acceso al Ecosistema Virtual - UNRC', help_text='Asunto del email de enrollamiento Moodle. Variables: {nombre}, {apellido}', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_asunto_password',
            field=models.CharField(blank=True, default='Nueva contraseña - UNRC', help_text='Asunto del email de reseteo de password. Variables: {nombre}, {apellido}, {upn}', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_plantilla_enrollamiento',
            field=models.TextField(blank=True, help_text='Plantilla HTML para email de enrollamiento en Moodle. Variables: {nombre}, {apellido}, {upn}, {moodle_url}, {cursos_html}. Pegar HTML completo.'),
        ),
    ]
