# Generated by Django 5.2.9 on 2025-12-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0027_setup_periodic_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email_payload',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='moodle_payload',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='teams_payload',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ultima_ingesta_aspirantes',
            field=models.DateTimeField(blank=True, editable=False, help_text='🕒 Timestamp de última ingesta exitosa de aspirantes (para consulta incremental)', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ultima_ingesta_ingresantes',
            field=models.DateTimeField(blank=True, editable=False, help_text='🕒 Timestamp de última ingesta exitosa de ingresantes (para consulta incremental)', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ultima_ingesta_preinscriptos',
            field=models.DateTimeField(blank=True, editable=False, help_text='🕒 Timestamp de última ingesta exitosa de preinscriptos (para consulta incremental)', null=True),
        ),
    ]
