# Generated by Django 5.2.9 on 2025-12-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0028_remove_alumno_email_payload_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la tarea personalizada', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, la tarea se ejecutará según la periodicidad configurada')),
                ('tipo_usuario', models.CharField(choices=[('preinscripto', 'Preinscriptos'), ('aspirante', 'Aspirantes'), ('ingresante', 'Ingresantes'), ('alumno', 'Alumnos'), ('todos', 'Todos')], default='todos', help_text='Tipo de usuario al que aplicar la tarea', max_length=20)),
                ('accion', models.CharField(choices=[('ingesta_sial', 'Ingestar desde SIAL/UTI'), ('crear_usuario_teams', 'Crear Usuario en Teams'), ('enviar_email', 'Enviar Email de Bienvenida'), ('activar_servicios', 'Activar Servicios (Teams+Email)'), ('moodle_enroll', 'Enrollar en Moodle'), ('resetear_password', 'Resetear Contraseña')], help_text='Acción a ejecutar sobre los usuarios seleccionados', max_length=30)),
                ('fecha_desde', models.DateTimeField(blank=True, help_text='Para ingesta SIAL: fecha desde la cual consultar (formato: YYYY-MM-DD HH:MM:SS)', null=True)),
                ('fecha_hasta', models.DateTimeField(blank=True, help_text="Para ingesta SIAL: fecha hasta la cual consultar (deja vacío para usar 'ahora')", null=True)),
                ('enviar_email', models.BooleanField(default=False, help_text='Para ingestas: enviar email de bienvenida a usuarios nuevos')),
                ('respetar_rate_limits', models.BooleanField(default=True, help_text='Usar el sistema de cola con rate limits (recomendado)')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('modificada_en', models.DateTimeField(auto_now=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, help_text='Última vez que se ejecutó esta tarea', null=True)),
                ('cantidad_ejecuciones', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha ejecutado esta tarea')),
                ('periodic_task', models.OneToOneField(blank=True, help_text='Tarea periódica de Celery Beat asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarea_personalizada', to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Tarea Personalizada',
                'verbose_name_plural': 'Tareas Personalizadas',
                'ordering': ('-creada_en',),
            },
        ),
    ]
