# Generated by Django 5.2.9 on 2025-12-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0029_tareapersonalizada'),
    ]

    operations = [
        # Comentado: campos ya eliminados en migración anterior
        # migrations.RemoveField(
        #     model_name='alumno',
        #     name='email_payload',
        # ),
        # migrations.RemoveField(
        #     model_name='alumno',
        #     name='moodle_payload',
        # ),
        # migrations.RemoveField(
        #     model_name='alumno',
        #     name='teams_payload',
        # ),
        migrations.AddField(
            model_name='configuracion',
            name='aspirantes_activar_moodle',
            field=models.BooleanField(default=False, help_text='🟠 Enrollar en Moodle automáticamente a nuevos aspirantes'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='aspirantes_activar_teams',
            field=models.BooleanField(default=False, help_text='🔵 Crear usuarios en Teams automáticamente para nuevos aspirantes'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ingresantes_activar_moodle',
            field=models.BooleanField(default=False, help_text='🟠 Enrollar en Moodle automáticamente a nuevos ingresantes'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ingresantes_activar_teams',
            field=models.BooleanField(default=False, help_text='🔵 Crear usuarios en Teams automáticamente para nuevos ingresantes'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='preinscriptos_activar_moodle',
            field=models.BooleanField(default=False, help_text='🟠 Enrollar en Moodle automáticamente a nuevos preinscriptos'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='preinscriptos_activar_teams',
            field=models.BooleanField(default=False, help_text='🔵 Crear usuarios en Teams automáticamente para nuevos preinscriptos'),
        ),
    ]
