# Generated by Django 5.2.9 on 2025-12-29 15:29

from django.db import migrations, models


def remove_fields_if_exist(apps, schema_editor):
    """Elimina campos solo si existen (migración idempotente)"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Obtener columnas existentes de la tabla Alumno
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='alumnos_alumno'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Eliminar solo los campos que existen
        fields_to_remove = ['email_payload', 'moodle_payload', 'teams_payload']
        for field_name in fields_to_remove:
            if field_name in existing_columns:
                cursor.execute(f"""
                    ALTER TABLE alumnos_alumno
                    DROP COLUMN {field_name}
                """)


def add_fields_if_not_exist(apps, schema_editor):
    """Agrega campos solo si no existen (migración idempotente)"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Obtener columnas existentes de la tabla Configuracion
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='alumnos_configuracion'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Definir campos a agregar
        fields_to_add = [
            ('deshabilitar_fallback_email_personal', "BOOLEAN DEFAULT FALSE"),
            ('email_asunto_bienvenida', "VARCHAR(255) DEFAULT 'Bienvenido/a a la UNRC'"),
            ('email_asunto_credenciales', "VARCHAR(255) DEFAULT 'Credenciales de acceso - UNRC'"),
            ('email_asunto_enrollamiento', "VARCHAR(255) DEFAULT 'Acceso al Ecosistema Virtual - UNRC'"),
            ('email_asunto_password', "VARCHAR(255) DEFAULT 'Nueva contraseña - UNRC'"),
            ('email_plantilla_enrollamiento', "TEXT DEFAULT ''"),
        ]

        # Agregar solo los campos que no existen
        for field_name, field_definition in fields_to_add:
            if field_name not in existing_columns:
                cursor.execute(f"""
                    ALTER TABLE alumnos_configuracion
                    ADD COLUMN {field_name} {field_definition}
                """)


def reverse_changes(apps, schema_editor):
    """Revierte los cambios (rollback)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0030_remove_alumno_email_payload_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, reverse_changes),
        migrations.RunPython(add_fields_if_not_exist, reverse_changes),
    ]
