# Generated by Django 5.2.8 on 2025-11-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia_uti', models.IntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_corto', models.CharField(blank=True, max_length=20)),
                ('codigo_uti', models.CharField(blank=True, max_length=50)),
                ('codigo_plan', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('codigo_uti', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plan_uti', models.IntegerField(db_index=True, unique=True)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_uti', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='core.materia')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='core.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=10)),
                ('dni', models.BigIntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localidad', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.modalidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_api', models.DateTimeField()),
                ('anio', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.alumno')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='core.comision')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='core.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia', 'comision', 'anio')},
            },
        ),
    ]
