# Generated by Django 5.2.8 on 2025-11-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Incripción', 'verbose_name_plural': 'Incripciones'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado_actual',
            field=models.CharField(choices=[('PRE', 'Preinscripto'), ('ASP', 'Aspirante'), ('ING', 'Ingresante'), ('ALU', 'Alumno')], db_index=True, default='PRE', max_length=3),
        ),
    ]
