# Generated by Django 5.2.9 on 2025-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('curso_moodle', models.CharField(help_text='Shortname del curso en Moodle', max_length=150)),
                ('carreras', models.JSONField(default=list, help_text='Lista de códigos de carrera (ej: CP, LE)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso de ingreso',
                'verbose_name_plural': 'Cursos de ingreso',
            },
        ),
        migrations.CreateModel(
            name='CursoRaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('curso_moodle', models.CharField(help_text='Shortname del curso en Moodle', max_length=150)),
                ('carreras', models.JSONField(default=list, help_text='Lista de códigos de carrera (ej: CP, LE)')),
                ('activo', models.BooleanField(default=True)),
                ('comision', models.CharField(help_text='Comisión que genera excepción (ej: 1, 2, COM-01)', max_length=50)),
            ],
            options={
                'verbose_name': 'Curso raro (excepción)',
                'verbose_name_plural': 'Cursos raros (excepciones)',
                'unique_together': {('comision', 'curso_moodle')},
            },
        ),
    ]
