# Generated by Django 5.2.9 on 2025-12-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoingreso',
            name='codigo_uti',
            field=models.CharField(blank=True, default='', help_text='Código UTI', max_length=30),
        ),
        migrations.AddField(
            model_name='cursoraro',
            name='codigo_uti',
            field=models.CharField(blank=True, default='', help_text='Código UTI', max_length=30),
        ),
    ]
