# Generated by Django 5.2.9 on 2025-12-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursoingreso_codigo_uti_cursoraro_codigo_uti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoingreso',
            name='codigo_uti',
        ),
        migrations.RemoveField(
            model_name='cursoraro',
            name='codigo_uti',
        ),
    ]
