# Generated by Django 5.2.9 on 2025-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_cursoingreso_codigo_uti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoingreso',
            name='comision',
            field=models.CharField(blank=True, default='', help_text='Comisión que aplica (dejar vacío si no corresponde)', max_length=50),
        ),
        migrations.AddField(
            model_name='cursoingreso',
            name='modalidades',
            field=models.JSONField(default=list, help_text='Lista de modalidades (ej: PRES, DIST)'),
        ),
        migrations.AddField(
            model_name='cursoraro',
            name='modalidades',
            field=models.JSONField(default=list, help_text='Lista de modalidades (ej: PRES, DIST)'),
        ),
        migrations.AlterField(
            model_name='cursoraro',
            name='comision',
            field=models.CharField(blank=True, default='', help_text='Comisión que aplica (dejar vacío si no corresponde)', max_length=50),
        ),
    ]
