# Generated by Django 5.2.9 on 2025-12-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cursoingreso_comision_cursoingreso_modalidades_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursoRaro',
        ),
    ]
