# Generated by Django 5.2.9 on 2025-12-04 14:29

from django.db import migrations, models


def copy_comision_to_comisiones(apps, schema_editor):
    CursoIngreso = apps.get_model('cursos', 'CursoIngreso')
    for curso in CursoIngreso.objects.all():
        valor = getattr(curso, 'comision', '')
        if valor:
            curso.comisiones = [str(valor).strip()]
            curso.save(update_fields=['comisiones'])


def copy_comisiones_to_comision(apps, schema_editor):
    CursoIngreso = apps.get_model('cursos', 'CursoIngreso')
    for curso in CursoIngreso.objects.all():
        coms = getattr(curso, 'comisiones', [])
        if coms:
            curso.comision = coms[0]
            curso.save(update_fields=['comision'])


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_delete_cursoraro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoingreso',
            name='comisiones',
            field=models.JSONField(default=list, help_text='Lista de comisiones (ej: 1, 2, 01, 02)'),
        ),
        migrations.RunPython(copy_comision_to_comisiones, copy_comisiones_to_comision),
        migrations.RemoveField(
            model_name='cursoingreso',
            name='comision',
        ),
    ]
