# Generated by Django 5.2.9 on 2025-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_cursoingreso_comision_cursoingreso_comisiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uti', models.IntegerField(help_text='ID de carrera desde API UTI/SIAL (ej: 2, 3, 4, 7, 8)', unique=True)),
                ('codigo', models.CharField(help_text='Código interno de la carrera (ej: LE, CP, LA, TGA, TGE)', max_length=10, unique=True)),
                ('nombre_completo', models.CharField(help_text='Nombre completo de la carrera', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Si la carrera está activa para nuevas inscripciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
