# Generated by Django 5.2.9 on 2025-12-12 15:08

from django.db import migrations


def populate_carreras(apps, schema_editor):
    """Populate Carrera table with initial data from CARRERAS_DICT."""
    Carrera = apps.get_model('cursos', 'Carrera')

    carreras_iniciales = [
        {"id_uti": 2, "codigo": "LE", "nombre_completo": "Licenciatura en Economía", "activo": True},
        {"id_uti": 3, "codigo": "CP", "nombre_completo": "Contador Público", "activo": True},
        {"id_uti": 4, "codigo": "LA", "nombre_completo": "Licenciatura en Administración", "activo": True},
        {"id_uti": 7, "codigo": "TGA", "nombre_completo": "Tecnicatura en Gestión Administrativa", "activo": True},
        {"id_uti": 8, "codigo": "TGE", "nombre_completo": "Tecnicatura en Gestión de Empresas", "activo": True},
    ]

    for data in carreras_iniciales:
        Carrera.objects.get_or_create(
            id_uti=data["id_uti"],
            defaults={
                "codigo": data["codigo"],
                "nombre_completo": data["nombre_completo"],
                "activo": data["activo"],
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove all carreras if migration is reversed."""
    Carrera = apps.get_model('cursos', 'Carrera')
    Carrera.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_carrera'),
    ]

    operations = [
        migrations.RunPython(populate_carreras, reverse_populate),
    ]
